version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: blog-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: blogpassword
      MYSQL_DATABASE: blog_platform
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: blogpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: blog-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  adminer:
    image: adminer:latest
    container_name: blog-adminer-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: blog-redis-commander-dev
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  mysql_data:
  redis_data: 